### ISSUE TITLE
 Invalid argument passed trying to extract an EXT4 image

### ISSUE THREAD

**Issue by blackeangel** [svoboda18/e2fstool#3]
All times I get error under Windows 10:

```
e2fstool 1.0.0 (30-Mar-2023)

Opening image file: 

e2fstool: Invalid argument while opening file (./system.img), try to increase your page/swap file.
```

run this:

`e2fstool.exe -c "./config_dir" "./system.img" "./system"`

**Comment by svoboda18** [comment]
Sorry for late response, but you should pass `-e` param for non-sparse images.

**Comment by blackeangel** [comment]
> Sorry for late response, but you should pass `-e` param for non-sparse images.

that is, the command for unpacking should be
```
e2fstool.exe -e -c "./config_dir" "./system.img" "./system"
```
?????

Please write a detailed user manual for working with your utility.

**Comment by svoboda18** [comment]
yes, did that solve your issue? I'm planning to add automatic image format selection so that you don't have to worry about which params to pass.

**Comment by blackeangel** [comment]
> yes, did that solve your issue? I'm planning to add automatic image format selection so that you don't have to worry about which params to pass.

No, I didn't try to add the parameter until it was possible.

It would be great!

I'll wait for the update then!

**Comment by svoboda18** [comment]
Till then, `e2fstool.exe -ec "./config_dir" "./system.img" "./system"` will extract raw ext4 `system.img`.
