### ISSUE TITLE
Add unpack Moto images

### ISSUE THREAD

**Issue by blackeangel** [svoboda18/e2fstool#4]
Please add support for unpacking MOTO images.
Below I attach a sparse image vendor.img
https://drive.google.com/file/d/1-1C-ZsTHj8ifcM4NI1099YpqXpSyqWRR/view?usp=drivesdk

Convector vendor_moto_raw.img to vendor_raw.img, written in python, which will help you understand what and how is happening to do this.
https://github.com/zachariasmaladroit/superrs-kitchen_free/blob/468aaea0b83e7044eff7ea12a5d55be547c8c6aa/tools/source/fixmoto.py

**Comment by svoboda18** [comment]
Should be okay with dbc3b5a and is available in [1.1](https://github.com/svoboda18/e2fstool/releases/tag/1.1).
